AllCops:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/LineLength:
  Max: 160
# Apparently this is a Ruby 3.0 thing?
Style/FrozenStringLiteralComment:
    Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes
